### ISSUE TITLE
tum-vi

### ISSUE THREAD

**Issue by zhuhongwei123** [jhch1995/UL-SLAM-Mono#3]
我有个疑问，我看到关于LSD线提取的论文很多，都是在针孔相机下的数据及进行的实验，比如EuroC和Tum-RGBD，我其实不太明白为什么鱼眼相机上没有人提取特征线，是因为畸变无法实现me

**Comment by jhch1995** [comment]
抱歉，最近在忙着写论文，刚看到消息。对于鱼眼相机，我们之前也做过相关测试，效果并不是很理想。感觉主要原因是畸变太大，导致裁切掉的图像区域过大，这样能够提取有效的线特征的部分会比较少。且经过畸变矫正得到的图像的质量往往相较于原图会差一点，所以也会影响线特征的提取和生成描述子的质量。当线特征提取的数目比较少，或者是生成描述子的质量不高的时候会导致，加入线特征基本不起作用甚至起负向作用。

**Comment by zhuhongwei123** [comment]
好的，谢谢你的回复！
